# -*- coding: utf-8 -*-
"""eda_goles_resultados.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1watJTTVwT2FGbpqgNjrNKWuEhsLN6tSy
"""





import matplotlib.pyplot as plt
import seaborn as sns

# Create a bar plot for match result distribution
plt.figure(figsize=(8, 6))
sns.barplot(x='Result', y='Number of Matches', data=result_distribution, palette='viridis', hue='Result', legend=False)
plt.title('Distribution of Match Results')
plt.xlabel('Match Result')
plt.ylabel('Number of Matches')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

import pandas as pd

# Load the CSV file
df_matches = pd.read_csv('/content/07_modeloA_final.csv')

# Display the first 5 rows to understand the data structure
print("First 5 rows of the DataFrame:")
display(df_matches.head())

# --- Goal Distribution ---

# Calculate total goals in each match
df_matches['TotalGoals'] = df_matches['home_score'] + df_matches['away_score']

# Distribution of total goals per match
goal_distribution = df_matches['TotalGoals'].value_counts().sort_index().reset_index()
goal_distribution.columns = ['Total Goals', 'Number of Matches']

# Distribution of home goals
home_goal_distribution = df_matches['home_score'].value_counts().sort_index().reset_index()
home_goal_distribution.columns = ['Home Goals', 'Number of Matches']

# Distribution of away goals
away_goal_distribution = df_matches['away_score'].value_counts().sort_index().reset_index()
away_goal_distribution.columns = ['Away Goals', 'Number of Matches']

print("\nDistribution of Total Goals Per Match:")
display(goal_distribution)

print("\nDistribution of Home Goals Per Match:")
display(home_goal_distribution)

print("\nDistribution of Away Goals Per Match:")
display(away_goal_distribution)

# --- Match Result Distribution ---

# Derive FTR from home_score and away_score
def get_match_result(row):
    if row['home_score'] > row['away_score']:
        return 'H'
    elif row['home_score'] < row['away_score']:
        return 'A'
    else:
        return 'D'

df_matches['FTR'] = df_matches.apply(get_match_result, axis=1)

# Map results to more descriptive names for clarity
result_map = {'H': 'Home Win', 'D': 'Draw', 'A': 'Away Win'}
df_matches['MatchResult'] = df_matches['FTR'].map(result_map)

# Distribution of match results
result_distribution = df_matches['MatchResult'].value_counts().reset_index()
result_distribution.columns = ['Result', 'Number of Matches']

print("\nDistribution of Match Results:")
display(result_distribution)